language: java

notifications:
  email:
    recipients:
    - jlee@antwerkz.com
    on_success: change
    on_failure: always

jdk:
  - openjdk11
env:
  - MONGODB=4.2.1 DRIVER=3.11.1
  - MONGODB=4.2.1 DRIVER=3.10.1
  - MONGODB=4.2.1 DRIVER=3.9.1
  - MONGODB=4.2.1 DRIVER=3.8.2
  - MONGODB=4.2.1 DRIVER=3.7.1
  - MONGODB=4.2.1 DRIVER=3.6.4
  - MONGODB=4.0.13 DRIVER=3.11.1
  - MONGODB=4.0.13 DRIVER=3.10.1
  - MONGODB=4.0.13 DRIVER=3.9.1
  - MONGODB=4.0.13 DRIVER=3.8.2
  - MONGODB=4.0.13 DRIVER=3.7.1
  - MONGODB=4.0.13 DRIVER=3.6.4
  - MONGODB=3.6.15 DRIVER=3.11.1
  - MONGODB=3.6.15 DRIVER=3.10.1
  - MONGODB=3.6.15 DRIVER=3.9.1
  - MONGODB=3.6.15 DRIVER=3.8.2
  - MONGODB=3.6.15 DRIVER=3.7.1
  - MONGODB=3.6.15 DRIVER=3.6.4


before_install:
  - sh ./mongo-travis.sh

script: mvn test
