language: java

notifications:
  email:
    recipients:
    - jlee@antwerkz.com
    on_success: change
    on_failure: always

jdk:
  - openjdk11
env:
  - MONGODB=4.2.1 DRIVER=3.11.1
  - MONGODB=4.2.1 DRIVER=3.10.1
  - MONGODB=4.2.1 DRIVER=3.9.1
  - MONGODB=4.2.1 DRIVER=3.8.2
  - MONGODB=4.2.1 DRIVER=3.7.1
  - MONGODB=4.2.1 DRIVER=3.6.4
  - MONGODB=4.2.1 DRIVER=3.4.3
  - MONGODB=4.0.13 DRIVER=3.11.1
  - MONGODB=4.0.13 DRIVER=3.10.1
  - MONGODB=4.0.13 DRIVER=3.9.1
  - MONGODB=4.0.13 DRIVER=3.8.2
  - MONGODB=4.0.13 DRIVER=3.7.1
  - MONGODB=4.0.13 DRIVER=3.6.4
  - MONGODB=4.0.13 DRIVER=3.4.3
  - MONGODB=3.6.15 DRIVER=3.11.1
  - MONGODB=3.6.15 DRIVER=3.10.1
  - MONGODB=3.6.15 DRIVER=3.9.1
  - MONGODB=3.6.15 DRIVER=3.8.2
  - MONGODB=3.6.15 DRIVER=3.7.1
  - MONGODB=3.6.15 DRIVER=3.6.4
  - MONGODB=3.6.15 DRIVER=3.4.3
  - MONGODB=3.4.23 DRIVER=3.11.1
  - MONGODB=3.4.23 DRIVER=3.10.1
  - MONGODB=3.4.23 DRIVER=3.9.1
  - MONGODB=3.4.23 DRIVER=3.8.2
  - MONGODB=3.4.23 DRIVER=3.7.1
  - MONGODB=3.4.23 DRIVER=3.6.4
  - MONGODB=3.4.23 DRIVER=3.4.3
  - MONGODB=3.2.22 DRIVER=3.11.1
  - MONGODB=3.2.22 DRIVER=3.10.1
  - MONGODB=3.2.22 DRIVER=3.9.1
  - MONGODB=3.2.22 DRIVER=3.8.2
  - MONGODB=3.2.22 DRIVER=3.7.1
  - MONGODB=3.2.22 DRIVER=3.6.4
  - MONGODB=3.2.22 DRIVER=3.4.3
  - MONGODB=3.0.15 DRIVER=3.11.1
  - MONGODB=3.0.15 DRIVER=3.10.1
  - MONGODB=3.0.15 DRIVER=3.9.1
  - MONGODB=3.0.15 DRIVER=3.8.2
  - MONGODB=3.0.15 DRIVER=3.7.1
  - MONGODB=3.0.15 DRIVER=3.6.4
  - MONGODB=3.0.15 DRIVER=3.4.3


before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 &> /dev/null &

script: mvn test
