language: java

notifications:
  email:
    recipients:
      - jlee@antwerkz.com
    on_success: change
    on_failure: always

jdk:
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14

before_script:
  - wget ${URL} -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 &> /dev/null &

script: mvn test

env:
  - MONGODB=4.2.8 DRIVER=4.0.4 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.2/multiverse/binary-amd64/mongodb-org-server_4.2.8_amd64.deb
  - MONGODB=4.2.8 DRIVER=3.12.5 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.2/multiverse/binary-amd64/mongodb-org-server_4.2.8_amd64.deb
  - MONGODB=4.2.8 DRIVER=3.11.2 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.2/multiverse/binary-amd64/mongodb-org-server_4.2.8_amd64.deb
  - MONGODB=4.2.8 DRIVER=3.10.2 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.2/multiverse/binary-amd64/mongodb-org-server_4.2.8_amd64.deb
  - MONGODB=4.2.8 DRIVER=3.9.1 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.2/multiverse/binary-amd64/mongodb-org-server_4.2.8_amd64.deb
  - MONGODB=4.2.8 DRIVER=3.8.2 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.2/multiverse/binary-amd64/mongodb-org-server_4.2.8_amd64.deb
  - MONGODB=4.2.8 DRIVER=3.7.1 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.2/multiverse/binary-amd64/mongodb-org-server_4.2.8_amd64.deb
  - MONGODB=4.0.19 DRIVER=4.0.4 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.0/multiverse/binary-amd64/mongodb-org-server_4.0.19_amd64.deb
  - MONGODB=4.0.19 DRIVER=3.12.5 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.0/multiverse/binary-amd64/mongodb-org-server_4.0.19_amd64.deb
  - MONGODB=4.0.19 DRIVER=3.11.2 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.0/multiverse/binary-amd64/mongodb-org-server_4.0.19_amd64.deb
  - MONGODB=4.0.19 DRIVER=3.10.2 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.0/multiverse/binary-amd64/mongodb-org-server_4.0.19_amd64.deb
  - MONGODB=4.0.19 DRIVER=3.9.1 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.0/multiverse/binary-amd64/mongodb-org-server_4.0.19_amd64.deb
  - MONGODB=4.0.19 DRIVER=3.8.2 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.0/multiverse/binary-amd64/mongodb-org-server_4.0.19_amd64.deb
  - MONGODB=4.0.19 DRIVER=3.7.1 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/4.0/multiverse/binary-amd64/mongodb-org-server_4.0.19_amd64.deb
  - MONGODB=3.6.18 DRIVER=4.0.4 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.6/multiverse/binary-amd64/mongodb-org-server_3.6.18_amd64.deb
  - MONGODB=3.6.18 DRIVER=3.12.5 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.6/multiverse/binary-amd64/mongodb-org-server_3.6.18_amd64.deb
  - MONGODB=3.6.18 DRIVER=3.11.2 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.6/multiverse/binary-amd64/mongodb-org-server_3.6.18_amd64.deb
  - MONGODB=3.6.18 DRIVER=3.10.2 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.6/multiverse/binary-amd64/mongodb-org-server_3.6.18_amd64.deb
  - MONGODB=3.6.18 DRIVER=3.9.1 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.6/multiverse/binary-amd64/mongodb-org-server_3.6.18_amd64.deb
  - MONGODB=3.6.18 DRIVER=3.8.2 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.6/multiverse/binary-amd64/mongodb-org-server_3.6.18_amd64.deb
  - MONGODB=3.6.18 DRIVER=3.7.1 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.6/multiverse/binary-amd64/mongodb-org-server_3.6.18_amd64.deb
  - MONGODB=3.4.24 DRIVER=4.0.4 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.4/multiverse/binary-amd64/mongodb-org-server_3.4.24_amd64.deb
  - MONGODB=3.4.24 DRIVER=3.12.5 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.4/multiverse/binary-amd64/mongodb-org-server_3.4.24_amd64.deb
  - MONGODB=3.4.24 DRIVER=3.11.2 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.4/multiverse/binary-amd64/mongodb-org-server_3.4.24_amd64.deb
  - MONGODB=3.4.24 DRIVER=3.10.2 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.4/multiverse/binary-amd64/mongodb-org-server_3.4.24_amd64.deb
  - MONGODB=3.4.24 DRIVER=3.9.1 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.4/multiverse/binary-amd64/mongodb-org-server_3.4.24_amd64.deb
  - MONGODB=3.4.24 DRIVER=3.8.2 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.4/multiverse/binary-amd64/mongodb-org-server_3.4.24_amd64.deb
  - MONGODB=3.4.24 DRIVER=3.7.1 URL=https://repo.mongodb.org/apt/ubuntu/dists/xenial/mongodb-org/3.4/multiverse/binary-amd64/mongodb-org-server_3.4.24_amd64.deb
