language: java

notifications:
  email:
    recipients:
      - jlee@antwerkz.com
    on_success: change
    on_failure: always

jdk:
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15

script: bin/travis-build.sh

env:
  - MONGODB=4.4.1 DRIVER=4.1.0
  - MONGODB=4.4.1 DRIVER=4.0.5
  - MONGODB=4.4.1 DRIVER=3.12.6
  - MONGODB=4.4.1 DRIVER=3.11.2
  - MONGODB=4.4.1 DRIVER=3.10.2
  - MONGODB=4.2.8 DRIVER=4.1.0
  - MONGODB=4.2.8 DRIVER=4.0.5
  - MONGODB=4.2.8 DRIVER=3.12.6
  - MONGODB=4.2.8 DRIVER=3.11.2
  - MONGODB=4.2.8 DRIVER=3.10.2
  - MONGODB=4.0.19 DRIVER=4.1.0
  - MONGODB=4.0.19 DRIVER=4.0.5
  - MONGODB=4.0.19 DRIVER=3.12.6
  - MONGODB=4.0.19 DRIVER=3.11.2
  - MONGODB=4.0.19 DRIVER=3.10.2
  - MONGODB=3.6.18 DRIVER=4.1.0
  - MONGODB=3.6.18 DRIVER=4.0.5
  - MONGODB=3.6.18 DRIVER=3.12.6
  - MONGODB=3.6.18 DRIVER=3.11.2
  - MONGODB=3.6.18 DRIVER=3.10.2
