language: java

notifications:
  email:
    recipients:
    - jlee@antwerkz.com
    on_success: change
    on_failure: always

jdk:
  - openjdk11
env:
  - MONGODB=4.2 DRIVER=3.11.1
#  - MONGODB=4.2 DRIVER=3.10.1
#  - MONGODB=4.2 DRIVER=3.9.1
#  - MONGODB=4.2 DRIVER=3.8.2
#  - MONGODB=4.2 DRIVER=3.7.1
#  - MONGODB=4.2 DRIVER=3.6.4
#  - MONGODB=4.2 DRIVER=3.4.3
#  - MONGODB=4.0 DRIVER=3.11.1
#  - MONGODB=4.0 DRIVER=3.10.1
#  - MONGODB=4.0 DRIVER=3.9.1
#  - MONGODB=4.0 DRIVER=3.8.2
#  - MONGODB=4.0 DRIVER=3.7.1
#  - MONGODB=4.0 DRIVER=3.6.4
#  - MONGODB=4.0 DRIVER=3.4.3
#  - MONGODB=3.6 DRIVER=3.11.1
#  - MONGODB=3.6 DRIVER=3.10.1
#  - MONGODB=3.6 DRIVER=3.9.1
#  - MONGODB=3.6 DRIVER=3.8.2
#  - MONGODB=3.6 DRIVER=3.7.1
#  - MONGODB=3.6 DRIVER=3.6.4
#  - MONGODB=3.6 DRIVER=3.4.3
#  - MONGODB=3.4 DRIVER=3.11.1
#  - MONGODB=3.4 DRIVER=3.10.1
#  - MONGODB=3.4 DRIVER=3.9.1
#  - MONGODB=3.4 DRIVER=3.8.2
#  - MONGODB=3.4 DRIVER=3.7.1
#  - MONGODB=3.4 DRIVER=3.6.4
#  - MONGODB=3.4 DRIVER=3.4.3
#  - MONGODB=3.2 DRIVER=3.11.1
#  - MONGODB=3.2 DRIVER=3.10.1
#  - MONGODB=3.2 DRIVER=3.9.1
#  - MONGODB=3.2 DRIVER=3.8.2
#  - MONGODB=3.2 DRIVER=3.7.1
#  - MONGODB=3.2 DRIVER=3.6.4
#  - MONGODB=3.2 DRIVER=3.4.3
#  - MONGODB=3.0 DRIVER=3.11.1
#  - MONGODB=3.0 DRIVER=3.10.1
#  - MONGODB=3.0 DRIVER=3.9.1
#  - MONGODB=3.0 DRIVER=3.8.2
#  - MONGODB=3.0 DRIVER=3.7.1
#  - MONGODB=3.0 DRIVER=3.6.4
#  - MONGODB=3.0 DRIVER=3.4.3


before_install:
  - mongo admin --eval 'db.shutdownServer();'
  - wget -qO - https://www.mongodb.org/static/pgp/server-${MONGODB}.asc | sudo apt-key add -
  - echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/${MONGODB} multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-${MONGODB}.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org
  - sudo service mongod start
  - dpkg --get-selections | grep mongo

script: mvn test
