language: java

notifications:
  email:
    recipients:
      - jlee@antwerkz.com
    on_success: change
    on_failure: always

jdk:
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14

env:
  - MONGODB=4.0.5 DRIVER=4.0.3
  - MONGODB=4.0.5 DRIVER=3.12.2
  - MONGODB=4.0.5 DRIVER=3.11.1
  - MONGODB=4.0.5 DRIVER=3.10.1
  - MONGODB=4.0.5 DRIVER=3.9.1
  - MONGODB=4.0.5 DRIVER=3.8.2
  - MONGODB=4.0.5 DRIVER=3.7.1
  - MONGODB=4.0.5 DRIVER=3.6.4
  - MONGODB=3.6.10 DRIVER=4.0.3
  - MONGODB=3.6.10 DRIVER=3.12.2
  - MONGODB=3.6.10 DRIVER=3.11.1
  - MONGODB=3.6.10 DRIVER=3.10.1
  - MONGODB=3.6.10 DRIVER=3.9.1
  - MONGODB=3.6.10 DRIVER=3.8.2
  - MONGODB=3.6.10 DRIVER=3.7.1
  - MONGODB=3.6.10 DRIVER=3.6.4
  - MONGODB=3.4.18 DRIVER=4.0.3
  - MONGODB=3.4.18 DRIVER=3.12.2
  - MONGODB=3.4.18 DRIVER=3.11.1
  - MONGODB=3.4.18 DRIVER=3.10.1
  - MONGODB=3.4.18 DRIVER=3.9.1
  - MONGODB=3.4.18 DRIVER=3.8.2
  - MONGODB=3.4.18 DRIVER=3.7.1
  - MONGODB=3.4.18 DRIVER=3.6.4

before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 &> /dev/null &

script: mvn test
