language: java

notifications:
  email:
    recipients:
      - jlee@antwerkz.com
    on_success: change
    on_failure: always

jdk:
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14

before_script:
  - wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-${MONGODB} -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 &

script: mvn test

env:
