# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: MorphiaCI

on:
  push:
    branches: [ master, github-actions-test ]
  pull_request:
    branches: [ master ]

jobs:
