# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Dependabot Check

on: [ pull_request ]

jobs:
  Morphia:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    strategy:
      matrix:
        java: [ 11, 17 ]
        mongo: [ 4.4.9, 4.2.16, 4.0.27 ]
        driver: [ 4.3.3 ]
    name: "Tests on JDK ${{ matrix.java }}, MDB: ${{ matrix.mongo }}, Driver: ${{ matrix.driver }})"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: \${{ runner.os }}-m2-\${{ hashFiles('**/pom.xml') }}
          restore-keys: \${{ runner.os }}-m2
      - name: Compile Code
        run: mvn install -DskipTests
      - name: Run Tests
        env:
          MONGODB: ${{ matrix.mongo }}
        run: mvn surefire:test -Ddriver.version=${{ matrix.driver }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: mongo-logs-${{matrix.java}}-${{matrix.mongo}}-${{matrix.driver}}
          path: |
            core/target/**/*.log
            core/target/**/*.err
          retention-days: 5
  Quality:
    name: Style Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: \${{ runner.os }}-m2-\${{ hashFiles('**/pom.xml') }}
          restore-keys: \${{ runner.os }}-m2
      - name: Install Plugins
        run: mvn install -DskipTests --file pom.xml
      - name: Quality Checks
        run: mvn -Pquality --file core/pom.xml
