# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Tests and Style Checks

on: [ push, pull_request ]

jobs:
  Morphia:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 15 ]
        mongo: [ 4.4.4, 4.2.13, 4.0.23, 3.6.23 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: \${{ runner.os }}-m2-\${{ hashFiles('**/pom.xml') }}
          restore-keys: \${{ runner.os }}-m2
      - name: Build with Maven
        env:
          MONGODB: ${{ matrix.mongo }}
        run: mvn -B verify --file pom.xml
      - name: List core/target/mongo contents
        if: always()
        run: find core/target/
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: mongo-logs-${{matrix.java}}-${{matrix.mongo}}
          path: |
            core/target/mongo.log
            core/target/mongo/mongo.log
            core/target/mongo/mongo.err
            core/target/mongo/*/mongo.log
            core/target/mongo/*/mongo.err
          retention-days: 5
  Quality:
    name: Style Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: \${{ runner.os }}-m2-\${{ hashFiles('**/pom.xml') }}
          restore-keys: \${{ runner.os }}-m2
      - name: Install Plugins
        run: mvn install -DskipTests --file pom.xml
      - name: Quality Checks
        run: mvn -Pquality --file core/pom.xml
