# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Tests

on: [ push, pull_request ]

jobs:
  Morphia:
    name: "Test Morphia"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 15 ]
        mongo: [ 4.4.2, 4.2.11, 4.0.21, 3.6.21 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: \${{ runner.os }}-m2-\${{ hashFiles('**/pom.xml') }}
          restore-keys: \${{ runner.os }}-m2
      - name: Build with Maven
        env:
          MONGODB: ${{ matrix.mongo }}
        run: mvn -B verify --file pom.xml
  Quality:
    name: Run code quality checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: \${{ runner.os }}-m2-\${{ hashFiles('**/pom.xml') }}
          restore-keys: \${{ runner.os }}-m2
      - name: Install Plugins
        run: mvn install -DskipTests --file pom.xml
      - name: Quality Checks
        run: mvn -Pquality --file core/pom.xml
  Changes:
    name: "Generate changes for this version"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: \${{ runner.os }}-m2-\${{ hashFiles('**/pom.xml') }}
          restore-keys: \${{ runner.os }}-m2
      - name: Install Plugins
        run: mvn install -DskipTests --file pom.xml
      - name: Configure Credentials
        run: echo "${{ secrets.CREDENTIALS }}" > ~/.github
      - name: Generate Changes
        run: mvn issues:generate -DskipTests --file core/pom.xml
      - name: Archive Changes
        uses: actions/upload-artifact@v2
        with:
          name: changes
          path: Changes-*.md
  Docs:
    name: Trigger the docs build
    runs-on: ubuntu-latest
    steps:
      - name: Invoke antora build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Docs
          repo: MorphiaOrg/morphia-docs
          token: ${{ secrets.PUSH_TOKEN }}
          ref: refs/heads/master
  Audits:
    name: Trigger the audit job
    runs-on: ubuntu-latest
    steps:
      - name: Invoke audits
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Audits
          repo: MorphiaOrg/morphia-audit
          token: ${{ secrets.PUSH_TOKEN }}
